distributions:
  equal_distribution:
    formula: "./scripts/equal_distribution.sh"
    base: 800
    amp: 200
  sinusoidal:
    formula: "./scripts/sinusoidal.sh" # C = Baseline (min), A = Amplitude
    base: 2000
    amp: 500
executor:
  name: "daily_health_simulation"
  execution-pattern: "linear"
  duration: 500
  steps:
    - distribution: "equal_distribution"
      duration: 100
    - distribution: "sinusoidal"
      duration: 400